version: "2"
services:
  web:
    container_name: gameoflifeContainerRec
    build: .
    restart: always 
    image: gameoflifeContainer:$VERSION
    ports:
      - 8013:8082
    networks:
      app_net:
        ipv4_address: 10.0.1.3
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24
        gateway: 10.0.1.1

